### PR TITLE
useFela function definition

### PR DESCRIPTION
**Pull request by reinhard**
## Description
Add Typescript defintion for useFela to react-fela index.d.ts

## Example
If required, add a code example or a link to a working example (repository).

```javascript
// your code 
```

## Packages
List all packages that have been changed.

- 

## Versioning
None / Patch / Minor / Major

## Checklist

- [ ] The code was formatted using Prettier (`yarn run format`)
- [ ] The code has no linting errors (`yarn run lint`)
- [ ] All tests are passing (`yarn run test`) 
- [ ] There are no flow-type errors (`yarn run flow`)

#### Changes
If one of the following checks doesn't make sense due to the type of PR, just check them.

- [ ] Tests have been added/updated
- [ ] Documentation has been added/updated
- [ ] My changes have proper flow-types

### CODE REVIEW

**Comment by rofrischmann** [comment]
Great, thank you!

**Comment by LiorCohen** [comment]
Did you guys push this change to NPM?

I'm current using `react-fela@10.2.1` and `node_modules/react-fela/index.d.ts` does not have an export for `useFela`.

TIA

**Comment by reinhard** [comment]
@LiorCohen The pull request has been merged with master but @rofrischmann has not released Fela yet.

**Comment by rofrischmann** [comment]
Going to ship that this evening, so stay tuned for a version update :)

**Pull request merged**
