### PR TITLE
added fela-enzyme

### PR DESCRIPTION
**Pull request by HamidAghdaee**
## Description
This PR provides new utilities to fix this issue:
https://github.com/rofrischmann/fela/issues/494

I have not updated this documentation: http://fela.js.org/docs/recipes/TestingFelaComponents.html

Once we land on something we agree, I'll do so.

## Example
https://github.com/HamidAghdaee/cf-weather

```javascript
import React from 'react';
import { felaShallow}  from 'fela-enzyme';
import { createComponent } from 'react-fela';

const theme = {
  fontSizes: [10, 12, 14, 16, 20, 24, 32, 48, 64, 80],
  color: {
    grass: '#9BCA3E',
    black: '#000'
  },
  fontSize: '15px'
};

const Div = createComponent(() => ({ color: 'black' }));
const { wrapper, snapshot } = felaShallow(<Div />, {}, theme);
expect(snapshot(wrapper)).toMatchSnapshot();

// Object {
//   "component": <div
//     className="a"
//   />,
//   "styles": "
// .a {
//   color: black
// }
// ",
// }

```

#### Major
fela-enzyme: 1.0.0

## Checklist

- [x] The code was formatted using Prettier (`yarn run format`)
- [x] The code has no linting errors (`yarn run lint`)
- [x] All tests are passing (`yarn run test`) 
- [x] There are no flow-type errors (`yarn run flow`)

#### Changes
If one of the following checks doesn't make sense due to the type of PR, just check them.

- [x] Tests have been added/updated
- [x] Documentation has been added/updated
- [x] My changes have proper flow-types

thanks

### CODE REVIEW

**Comment by rofrischmann** [comment]
Yeah, I like that one! Have you seen https://github.com/rofrischmann/fela/pull/582 as well? It's a way more opinionated tool with minimal formatted output that's kind of what we're using at work nowadays. Guess the core benefit with enzyme is that you're able to simulate clicks and stuff right?

**Comment by HamidAghdaee** [comment]
@rofrischmann yes. With this PR you get all the benefits of enzyme + fela rendered styles. The other solution looks elegant, it always does a deep render however, right? I believe the main benefit of my PR is the ability to do shallow rendering.

**Comment by rofrischmann** [comment]
Yeah right! I guess we should merge both simultaneously and update the Testing docs together. It could be both smaller and simpler :P

**Comment by HamidAghdaee** [comment]
@rofrischmann Sounds great. Whatever you see fit. Let me know how you want to proceed. Two things:

1. currently I haven't added flow types to any of my code. Is this something you'd like me to do?
2. I've made the package peer dependent on any version of react, enzyme and enzyme-to-json. This seems right to me. I don't think this package should be making explicit dependencies on these. I could however be more explicit what versions of these packages I've tested these with. But I have made explicit dependencies on fela. fela-tools and react-fela. I'm really not sure what values are correct for these dependencies. Perhaps they should also be peerdependencies.

**Comment by rofrischmann** [comment]
Would be cool if you could add some Flow types to better ensure this package works fine in the future.
Let's collaborate on updating those docs, how does that sound? We could chat on Gitter or Twitter e.g.

**Pull request merged**
