### PR TITLE
460 ts connect definition

### PR DESCRIPTION
**Pull request by sgrishchenko**
see https://github.com/rofrischmann/fela/issues/460

#### Minor
- fela-bindings

#### Patch
- react-fela
- preact-fela
- inferno-fela

### CODE REVIEW

**Comment by rofrischmann** [comment]
Oh yeah, thanks for the typings!
The proposed API change also looks fine to me, I will test it later and merge it =)

**Comment by sgrishchenko** [comment]
My colleague found an error in my typing. This happened because I did not properly test the typing. The project does not yet have a suitable infrastructure for verifying typing. Let's roll back the commit of merge, will I fix the error and additionally prepare a separate plug-and-play module?

**Comment by sgrishchenko** [comment]
Sorry

**Comment by rofrischmann** [comment]
A TypeScript example would be great! Looking forward to see it. No worries, didn’t release it anyways :)

**Comment by sgrishchenko** [comment]
ready, see https://github.com/rofrischmann/fela/pull/463

**Pull request merged**
