### PR TITLE
Simplified FelaComponent API

### PR DESCRIPTION
**Pull request by rofrischmann**
## Description
This PR implements major changes in FelaComponent and FelaTheme with partial backwards-compatibility and incremental migration support.
It also implements jest-react-fela for all tests and adds support for objects to combineRules.
This replaces https://github.com/rofrischmann/fela/pull/597 as a more adoptable incremental approach.

#### Major
- fela-bindings
- react-fela
- preact-fela
- inferno-fela

## Checklist

- [x] The code was formatted using Prettier (`yarn run format`)
- [x] The code has no linting errors (`yarn run lint`)
- [x] All tests are passing (`yarn run test`) 
- [x] There are no flow-type errors (`yarn run flow`)

#### Changes
If one of the following checks doesn't make sense due to the type of PR, just check them.

- [x] Tests have been added/updated
- [x] Documentation has been added/updated
- [x] My changes have proper flow-types

### CODE REVIEW

**Comment by TxHawks** [comment]
@rofrischmann is this ready for review? I can try and look at it later today or tomorrow

**Comment by TxHawks** [comment]
Did you close this intentionally?

**Comment by rofrischmann** [comment]
Oh woops, miss clicked :D

**Comment by TxHawks** [comment]
Still going through this, but one thing I noticed is that the FelaComponent codemod doesn't handle the depreciation of `render` in favor of `children` and `as`

**Comment by rofrischmann** [comment]
Oh true, I might copy that from the FelaTheme codemod, thanks for mentioning!
It also doesn't cover all use cases properly.

e.g. 
```javascript
// theme => ({ color: theme.primary })
import themeFunction from './themeFunction'

<FelaComponent style={themeFunction} />
```

won't transform the themeFunction (as it's impossible with Babel).

**Comment by rofrischmann** [comment]
Yeah, but it’s almost impossible with Babel codemods. That would require code analysis and sth. like Webpack after all...

**Pull request merged**
