### PR TITLE
Docs: Testing Components

### PR DESCRIPTION
**Pull request by derek-duncan**
Inspired by #247. WIP. Feel free to review/contribute.

### CODE REVIEW

**Comment by rofrischmann** [comment]
Like that :) Tell me as soon as I can merge it. Or is it finished already?

**Comment by tajo** [comment]
@rofrischmann  Wait, it's actually missing the test examples part. :)

**Comment by rofrischmann** [comment]
@derek-duncan any progress on this one :P?

**Comment by derek-duncan** [comment]
@rofrischmann yes sorry about the delay. I started to finish the examples, but I've ran into a bunch of different use cases while using fela at work. Writing some notes on those as well.

**Comment by derek-duncan** [comment]
okay working on this now. should have some updates shortly

**Comment by derek-duncan** [comment]
This is ready for another set of eyes 🎉

**Comment by tajo** [comment]
Great job! LGTM.

**Comment by rofrischmann** [comment]
Wow that's a hell lot of stuff! I'll further read later today, but really looks promising :)

**Comment by rofrischmann** [comment]
Great one. Thank you :)

**Pull request merged**
