### PR TITLE
Connect typing improvements

### PR DESCRIPTION
**Pull request by sgrishchenko**
## Description
This pull request contains a set of `connect` typing improvements:

- theme injected automaticalliy into component
- `Rules` type improved
- supported [Reconnection Pattern](http://fela.js.org/docs/api/bindings/connect.html) in typings
- included renderer argument to TRule and TMultiRule (see #625)
- updated typescript example

## Example
before:
```javascript
import {connect, withTheme} from 'react-fela'

const MyComponent = ({styles, theme}) => {/* some content */}

const ConnectedMyComponent = connect({/* some rules */})(
  withTheme(MyComponent)
)
```
after:
```javascript
import {connect} from 'react-fela'

const MyComponent = ({styles, theme}) => {/* some content */}

const ConnectedMyComponent = connect({/* some rules */})(MyComponent)
```

## Packages
List all packages that have been changed.

- fela-bindings
- react-fela
- preact-fela
- inferno-fela

## Versioning
Minor

## Checklist

- [x] The code was formatted using Prettier (`yarn run format`)
- [x] The code has no linting errors (`yarn run lint`)
- [x] All tests are passing (`yarn run test`) 
- [x] There are no flow-type errors (`yarn run flow`)

#### Changes
If one of the following checks doesn't make sense due to the type of PR, just check them.

- [x] Tests have been added/updated
- [x] Documentation has been added/updated
- [x] My changes have proper flow-types

### CODE REVIEW

**Comment by rofrischmann** [comment]
Nice! Thanks for the work :)

**Comment by rofrischmann** [comment]
@sgrishchenko Does this also solve #625?

**Comment by sgrishchenko** [comment]
I think yes, this solve #625 main issue topic, but now I read the issue carefully and saw that there were problems with keyframe typing. I think I will make an additional pull request in the near future to close this issue.

**Comment by rofrischmann** [comment]
Ok great! Thank you. I will release this stuff hopefully today.

**Pull request merged**
