### PR TITLE
Fixed media queries inside validator

### PR DESCRIPTION
**Pull request by tiagojsalmeida**
Validate media queries as nested property.

### CODE REVIEW

**Comment by rofrischmann** [comment]
Thanks a lot :)

**Comment by tiagojsalmeida** [comment]
Thank you for always improving fela @rofrischmann !

**Comment by tiagojsalmeida** [comment]
@rofrischmann let me know when it's published.

**Comment by tiagojsalmeida** [comment]
@rofrischmann would it be possible to make a release?

**Pull request merged**
