### PR TITLE
Bumps styleguidist and polished to latest and minor order fix with plugins. 

### PR DESCRIPTION
**Pull request by aga5tya**

### CODE REVIEW

**Comment by rofrischmann** [comment]
@aga5tya Is this still up-to-date and mergeable?

**Comment by aga5tya** [comment]
@rofrischmann Please hold on this for now, il sync to the latest once and update the PR.

**Comment by rofrischmann** [comment]
Hows the current status :) Might not be here next weeks so I'd like to merge open PRs before^^

**Comment by aga5tya** [comment]
@rofrischmann, Had got stuck with some personal chores, hence the delay. I have synced updated the PR, Kindly review.

**Comment by rofrischmann** [comment]
Looks fine :) Thank you!

**Pull request merged**
