### PR TITLE
prevent collisions in fela-monolithic and babel-plugin-fela

### PR DESCRIPTION
**Pull request by sgrishchenko**
## Description
Generation of unique hash keys with collision prevention is encapsulated in the **fela-utils** module. Improved the formation of pretty selectors for the `connect` function in **fela-bindings**.  Enhanced version of **Lerna** ).

#### Minor
fela-bindings
fela-utils

#### Patch
babel-plugin-fela
fela-monolithic

## Checklist

- [x] The code was formatted using Prettier (`yarn run format`)
- [x] The code has no linting errors (`yarn run lint`)
- [x] All tests are passing (`yarn run test`) 
- [x] There are no flow-type errors (`yarn run flow`)

#### Changes
If one of the following checks doesn't make sense due to the type of PR, just check them.

- [x] Tests have been added/updated
- [x] Documentation has been added/updated
- [x] My changes have proper flow-types

### CODE REVIEW

**Comment by rofrischmann** [comment]
Amazing, thank you!

**Comment by tiagojsalmeida** [comment]
Hey guys!
`fela-monolithic` had breaking changes since the classnames changed, having a `_` prefix now after this PR.

**Comment by rofrischmann** [comment]
Oh damn, I forgot to add that. But at least it doesn't break anything (except for tests). The underscore should make your class names safe actually. Thanks for mentioning anyways =)

**Comment by tiagojsalmeida** [comment]
🙌
Thanks for all improvments!

**Pull request merged**
